### ISSUE TITLE
Can't recognize Logitech C270 webcam

### ISSUE THREAD

**Issue by Spacebody** [bqlabs/horus#110]
Ran on respbian on Pi 3, the software cannot recoginze  the camera and prompted that chosen wrong camera, but there was only one camera connected to Pi by usb. Can someone tell me how to fix it?

**Comment by carlosen14** [comment]
There are no drivers for that camera to run on Linux, installed any other third party drivers?, can you use the camera with other app?

**Comment by Spacebody** [comment]
I found the drivers could only work in specified Arduino board. Thanks.

**Comment by carlosen14** [comment]
Drivers? Don't you mean frimware for Arduino?, and yes, the firmware works with an Arduino UNO connected to a ZUM SCAN. Maybe you can make your own, it is open hardware.

http://diwo.bq.com/zum-scan-released

**Comment by Spacebody** [comment]
Yes.
