### ISSUE TITLE
camera connection unplugged

### ISSUE THREAD

**Issue by Jesus89** [bqlabs/horus#53]
rm -rf ~/.horus/
start horus
move to control workbench
try to connect
message -> camera unplugged

**Comment by nicanor-romero** [comment]
Fixed in 134941d0a1a518ec4e444659a6fc29a6dfafda92

**Comment by govanator** [comment]
How do i solve this? i have problem after problem withthis ciclop and horus, haven't been able to make 1 decent scan!

**Comment by Jesus89** [comment]
Hi,

There is not a new official version. If you are using Ubuntu you can install the development version. This version 0.2 is easy to use. Probably most of your problems will be solved. The commands for the installation are:

  sudo add-apt-repository ppa:bqlabs/horus-dev
  sudo apt-get update
  sudo apt-get upgrade

However, if you didn't have installed horus, you can try after these commands:

  sudo apt-get install horus

Please, for future feedback go to google group with more detail.

Regards.

**Comment by govanator** [comment]
How am i supposed to use these commands??
I found the source code for 0.2b1, i have a ubuntu virtual machine.
I know this isn't your fault jesus, but i think i am going to demand a refund.

**Comment by Jesus89** [comment]
Hi,

These are ubuntu commands. Must be executed in the terminal. It is needed native Ubuntu, not virtual machines because of the camera and usb drivers.

I suppose that you are a Windows or Mac user. I hope that official versions for Windows and Mac are available soon, but this is out my control.

Sorry about that.
