### ISSUE TITLE
configering Lasers

### ISSUE THREAD

**Issue by honda10** [bqlabs/horus#58]
I cannot calibrate the lasers during wizard mode. they will work at the end of set up.
 I am using windows 8.1 with a baud BT.ATmega328
 any help please
 Honda

**Comment by nicanor-romero** [comment]
Hi @honda10 , which version of Horus are you running?

**Comment by honda10** [comment]
Hello,Thankyou for your reply.The version I am running is 0.1.2.4. Build 259. Github 38df73b.General setting up of lazers seem to be a problem in all sections.thank you for supportHonda10 


     On Monday, 5 October 2015, 19:21, Nicanor Romero Venier <notifications@github.com> wrote:
   

 Hi @honda10 , which version of Horus are you running?—

**Comment by 1964nickuk** [comment]
Hi. Did you get this problem sorted. Ive just built mine and although I can turn the lasers on manualy I cant during calibration? Any ideas? Cheers

**Comment by honda10** [comment]
Hi.
I am sorry to say that I got side tracked learning about the 3D printer. However I my memory serves me correctly it was a computer problem, and it does not seem to like extension usb leads.
I will have to get back to it very soon as I have a couple of jobs for it.
Cheers

**Comment by 1964nickuk** [comment]
Thanks for getting back. It was the room lighting that was causing my problem. Now just need to improve the quality
Cheers
