### ISSUE TITLE
error message: Board not connected

### ISSUE THREAD

**Issue by Howardtsou** [bqlabs/horus#62]
When I hit the Connect button, there is an error message "The board is not connected. Please connect your board and select a valid Serial Name." 
My computer is win7.  I have installed the camera driver on "https://github.com/bqlabs/horus/blob/master/doc/installation/windows.md ".
In the Preferences window, The serial name is COM1. There is no other serial name can be chosen.
Baud rate is 115200, camera ID is 0. 
Can you help me with this ?

**Comment by Jesus89** [comment]
Try to burn the firmware.

**Comment by Howardtsou** [comment]
I have tried it. But I hit the "upload Firmware" button,  there is nothing happen. Is it normal to take lots of time to upload? It has taken 30 mins for uploading the firmware.
By the way, my fw file is downloaded form " http://diwo.bq.com/en/horus-fw-released/ ".
Now I don't know what's wrong with it.

**Comment by Howardtsou** [comment]
Sometimes, error message says that "you have probably selected the wrong board ." 
But, I have only one board, the serial menu has only one can be chosen, too.

**Comment by Taz5325** [comment]
Hi,
I have the same problem.

I use windows 7 or 8.1.

The port serial list is always clear.

**Comment by Taz5325** [comment]
Hi the same problem with windows vista.

I'll try an windows xp installation the next monday.

**Comment by Janndog** [comment]
Hey guys, Just got a Ciclop today, built and ready to go.
I have Ubuntu, and have installed Horus, until now everything went fine,
now I want to start scanning and have the same error as mentioned above.

I've tried reconnecting all the cables, burning the firmware, and resetting the board itself... to no avail.
I there anything possible?..

**Comment by Taz5325** [comment]
Hi.

For me, it's work. I just changed the usb cable.

**Comment by Janndog** [comment]
Wow!! Okay, the new USB cable fixed the problem!

**Comment by Taz5325** [comment]
Yes just a New usb cable.

**Comment by Jesus89** [comment]
:+1:

**Comment by Mrto789** [comment]
Hello, I just bought ciclop scanner, but I can not get Mattre on.
after assembly and electronic installation, I had trouble configuring the camera.
I always errors of this type of;
"you probably have selected the wrong camera, please select another Camera ID"
or "The bord is not connected".

I have win 10, horus 0.2b3 and Iws280

Help me please

**Comment by Mrto789** [comment]
![2016-04-20_12h37_28](https://cloud.githubusercontent.com/assets/18572617/14672022/6e0b3c48-06f5-11e6-8fbd-854e6ebc37b1.png)
![2016-04-20_12h38_20](https://cloud.githubusercontent.com/assets/18572617/14672023/6e0e8aec-06f5-11e6-9e41-46824267b58d.png)
![2016-04-20_12h42_22](https://cloud.githubusercontent.com/assets/18572617/14672024/6e113314-06f5-11e6-9984-2b9e90f32846.png)

**Comment by Jesus89** [comment]
Hi, try reinstall the drivers: http://support.logitech.com/en_us/product/hd-webcam-c270. And the computer.

Also select "Upload firmare" to load the firmware into the board.

**Comment by Jesus89** [comment]
Duplicated issue. #76.
