### ISSUE TITLE
instruction videos SPANISH ONLY

### ISSUE THREAD

**Issue by MarcusWolschon** [bqlabs/horus#64]
All instruction videos linked in
https://github.com/bqlabs/horus/wiki/Documentation
are in spanish only and only have spanish subtitles with no option to translate
them into any other language.

**Comment by Jesus89** [comment]
@MacarenaGB, can you add subtitles in more languages?

**Comment by zeus10** [comment]
sous titré en espagnol alors tout le monde peut traduire avec traducteur

**Comment by Jesus89** [comment]
Hi, you can find the updated documentation here: http://horus.readthedocs.io/.
