### ISSUE TITLE
Freeze of the video part of the application when ask 

### ISSUE THREAD

**Issue by deusyss** [bqlabs/horus#68]
Configuration:
-Linux Mint 17.3
-Follow installation instruction for Debian Like OS
-clone git repository and launch directly ./horus from this clone

When i ask to use the distorsion, i get error on my terminal. At this moment, video is out of order. We need to relaunch Horus.

Traceback (most recent call last):
  File "./src/horus/gui/util/video_view.py", line 44, in on_timer
    self.set_frame(frame)
  File "./src/horus/gui/util/image_view.py", line 64, in set_frame
    self.set_image(wx.ImageFromBuffer(width, height, frame))
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 3598, in ImageFromBuffer
    image = _core_._ImageFromBuffer(width, height, dataBuffer, alphaBuffer)
TypeError: expected a single-segment buffer object

**Comment by Jesus89** [comment]
Hi,

First, make sure that you have installed the last version of our OpenCV: https://github.com/bqlabs/opencv/wiki/Build.

I just find and fix the bug: b4ea0a8cd81a79282d68c15d1d3a22afcc93ef6f.

NOTE: all updates will be made in release/0.2 by now.

Thanks.
