### ISSUE TITLE
doble Webcam Logitech

### ISSUE THREAD

**Issue by bartbender** [bqlabs/horus#69]
Hola, cuando instalas el escáner cyclops en un equipo que ya dispone de una cámara Logitech , en mi caso una C525, Horus está detectando la cámara anterior en lugar de la C270 que incluye cyclops.
Se debería incluir una opción para seleccionar la cámara a utilizar por el programa en el Wizard.

Muchas gracias

**Comment by Jesus89** [comment]
Se puede seleccionar la cámara en el menú de preferencias.
Gracias por la sugerencia.

**Comment by Jesus89** [comment]
Incluido en la versión 0.2rc1
