### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by maddavo** [bqlabs/horus#71]
I am having great trouble getting the win32 package script working.  Can someone please point me to a Windows installer or binary?  Surely there is one somewhere.

**Comment by Neon22** [comment]
from help pdf
> Horus is installed on Windows by executing the “.exe” file that you can find under the downloads 
> section of 
> www.bq.com/gb/products/ciclop.html
> . Administrator permissions are required.
https://static-bqreaders.s3.amazonaws.com/file/ciclop/Horus_User_manual_EN.pdf

**Comment by maddavo** [comment]
? That link does not work.  It redirects to "http://www.bq.com/uk/" and I cannot find anything about ciclop there.  WHERE IS THE EXE?

**Comment by Jesus89** [comment]
Hi, you can find the latest executable version in the official documentation: http://horus.readthedocs.io > Install on Windows.

Note: development is recommended under Linux. If you want to execute the sources in Windows you may need to use https://www.cygwin.com/.
