### ISSUE TITLE
consider three lines

### ISSUE THREAD

**Issue by Neon22** [bqlabs/horus#72]
Please consider adding two more laser line modules one green and one 'blue'. (same approx location on rig).
Benefits:
- two more colours allows for better response on objects that do not reflect the Red well.
- the signal to noise increases from more samples.
- costs go up only marginally.
- you can consider recovering surface colour.

Issues:
- The three lasers do not require perfect alignment. (actually S/N surface reconstruction is better if not aligned).
- But they do require sep calibration.
- Scan is slightly slower as cycle through lasers and acquire three frames per step.
- Even adding one more laser will improve surface considerably.

**Comment by Jesus89** [comment]
Thanks for the suggestion. Probably I will add n-lasers management in the future.

Btw, if you are interested in going deeper, here you have the [scientific background](https://github.com/Jesus89/3DScanScience).

Regards.
