### ISSUE TITLE
Unable to connect board

### ISSUE THREAD

**Issue by Jerimon1998** [bqlabs/horus#74]
I had the scanner set up and working just fine, but now I can't get horus to connect to the board. I've tried switching usb cables (as had worked in a previous issue), uninstalling and reinstalling horus, and uploading firmware to the board (both installs, rejected since it cannot connect). The only serial port available is COM4, and I have double checked all connections, the baudrate, and the camera. Nothing seems to work.

**Comment by Jesus89** [comment]
Try reinstalling the drivers (FTDI and camera). Are you using a ZUM board or an Arduino?
Also you can use putty (http://www.putty.org/) to try to connect to the board with baud rate 115200.
If the error persist check the camera drivers: http://support.logitech.com/en_us/product/hd-webcam-c270

**Comment by Jerimon1998** [comment]
It is an arduino uno with the zum scan shield. The camera works (Horus connects to it before trying to connect to the board) and has a working video feed.

**Comment by Jerimon1998** [comment]
I have installed the software on a different computer and now the menu in Horus doesn't show a valid COM port at all. The putty software could not connect to either of my "guesses" at the serial port (Port_#0001.Hub_#0006 was the location information). The "address" of the board is 00000001, and Windows detects that there are no drivers for the device. It still shows up as a USB 2.0 Serial connection, though.
I will try tinkering with the arduino IDE to see if it can detect the board. At this point I'd expect that resetting and flashing the arduino may be the solution.

**Comment by Jerimon1998** [comment]
Nothing that I have tried seems to work. I have the IDE, I have PuTTY, and I have tried using Horus repeatedly. Windows cannot connect to it correctly, and is unable to install drivers, even from the IDE. The board still shows up as a device, just a driverless one.
Could the board just be faulty?

**Comment by Jesus89** [comment]
This issue is the same as #81. It will continue there.
