### ISSUE TITLE
Does not install on (K)ubuntu 15.10

### ISSUE THREAD

**Issue by techmod** [bqlabs/horus#75]
Unfortunately horus doesn install on a (K)ubuntu 15.10 machine due to opencv. It says that opencv and itś dependies aren't meant to be installed.

**Comment by Jesus89** [comment]
Hi, try this ppa: ppa:bqlabs/horus-dev.

**Comment by techmod** [comment]
Hi, I tried..still the same. Bash throws this:

`daniel@W520:~$ LANG=C sudo apt-get install horus
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 horus : Depends: python-opencv but it is not going to be installed
E: Unable to correct problems, you have held broken packages.`

**Comment by Jesus89** [comment]
First try to upgrade your system.

sudo add-apt-repository ppa:bqlabs/horus-dev
sudo apt-get update
sudo apt-get dist-upgrade

Also execute:

sudo apt-get -f install
sudo apt-get autoremove

Is all is OK, then try again.

**Comment by techmod** [comment]
Unfortunately this does not work here. Bash throws again:

daniel@W520:~$ LANG=C sudo apt-get -f install horus
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 horus : Depends: python-opencv but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by Jesus89** [comment]
All below commands have been executed correctly? What happens if you execute

sudo apt-get install python-opencv

**Comment by techmod** [comment]
It is always the same. Trying the install of opencv throws that there are unmet dependencies which won't be installed and/or broken packages. trying to install opencv only first throws an error because of the libs and that they won't be installed.

**Comment by Jesus89** [comment]
Can you execute without LANG=C?: sudo apt-get install python-opencv. I think there is a problem with your apt-get.

There is also a method (a bit tricky). You can download deb files and install it manually: https://launchpad.net/~bqlabs/+archive/ubuntu/horus-dev/+packages?field.name_filter=&field.status_filter=published&field.series_filter=vivid, with `sudo dpkg -i package.deb` in the correct order and then `sudo apt-get -f install`.

**Comment by techmod** [comment]
Executing the same without LANG=C throws the same error. LANG=C prints the output in english temporarily. i will try the deb.

**Comment by techmod** [comment]
Okay, i got it....Installed horus via qapt-deb-installer, then downloaded python_opencv and installed with the commands above. Now it starts. I will see if the device is functioning.

Thanks.

**Comment by Jesus89** [comment]
Ok. Great!
