### ISSUE TITLE
"The bord is not connected or please select another Camera ID"

### ISSUE THREAD

**Issue by Mrto789** [bqlabs/horus#76]
Hello, I just bought ciclop scanner,  but I just can not turn it on.
after assembly and electronic installation, I had trouble configuring the camera.
I always errors of this type of;
"you probably have selected the wrong camera, please select another Camera ID"
or "The bord is not connected".

I have win 10, horus 0.2b3 and Iws280

Help me please
![2016-04-20_12h37_28](https://cloud.githubusercontent.com/assets/18572617/14672220/c2f09478-06f6-11e6-9afb-9f46697d4130.png)
![2016-04-20_12h38_20](https://cloud.githubusercontent.com/assets/18572617/14672221/c2f3b82e-06f6-11e6-9fd8-9055cc8cb63b.png)
![2016-04-20_12h42_22](https://cloud.githubusercontent.com/assets/18572617/14672222/c2f5fb16-06f6-11e6-954a-8513e096ae81.png)

**Comment by Jesus89** [comment]
Hi, try reinstall the drivers: http://support.logitech.com/en_us/product/hd-webcam-c270. And the computer.

Also select "Upload firmare" to load the firmware into the board.

**Comment by Jesus89** [comment]
This issue is the same as #81. It will continue there.

**Comment by energist** [comment]
I have similar problem. "Board has wrong firmware or invalid baud rate"  I selected the only other board and uploaded the firmware.  I have also loaded Logitech drivers.  Still get the same message.  Win10, 32 bit, Horus 0.2rc1.  Any suggestions?
