### ISSUE TITLE
[Question] Support for other scanners 

### ISSUE THREAD

**Issue by luc-github** [bqlabs/horus#78]
Hola Jesus,
First thank you for this great project 
Sorry to bother but we are working to make horus working with Davinci 3D printer All in one (https://www.youtube.com/watch?v=GvYi7TQpffY) and have some questions

Currently  when flashing repetier FW the scanner functions are not working anymore because scan application need stock FW.
We have found all way to control the hardware laser 1 and 2, the turntable, the cameras look ok in horus.
So I am implementing the commands needed by horus in repetier FW, we are in early stage but I have couple of questions:
1 - any plan to put the GCODE commands in some preference file? for example
G1 Xnnn Fnnn  command is already used by printer so need to change to G201 Xnnn Fnnn,
also connection string to recognize FW prevent to use another FW
Acceleration command is not a standard GCODE, etc...
currently I modify board.py but in future would be interresting to just change settings in preferences

2 -  about previous point :
Can we implement this and push as PR to your github ? or do you prefer to stick on horus FW only ? 

3 -  I know currently only one cam is supported, but Davinci AiO has 2 cams : one on top side left one on bottom side right.
Do you think it will be a difficult task to support 2 cams ?

4 - Do you have any guidelines / suggestions for us in this implementation?  special points to check and / or modify to have good support ?

Again thanks for this great project

**Comment by Jesus89** [comment]
Hi, thank you for you interest in the project.

First, I am glad to see other open projects related to 3D scanning :)

I answer to your questions:

1 . I think it is an interesting idea to have Gcode command configuration in the profile. Also in the future more hex files can be included in the official Horus releases.

2. I will be glad to accept pull requests. We will discuss its functionality and implementation in those pr. Also it would be good to have a link to your FW source code. I is compatible with Arduino boards?

3. Including another camera could be a tricky issue because it needs a new structure. Each camera will needs its calibration parameters. An easy start would be to consider that system as 2 different scanners with different calibration parameters. A more interesting approach could be to reference the top camera homogeneous matrix to the one in the bottom. Probably this information will be interesting for you: https://github.com/Jesus89/3DScanScience.

4. I will create a "davinci" branch in the project to work on that before the release. I think more work will be done here: https://github.com/bqlabs/horus/tree/develop/src/horus/engine/driver. Also It would be nice to update this documentation http://horus.readthedocs.io with the new features added.

Regards.

**Comment by luc-github** [comment]
Hi Jesus - thanks a lot for your feedback - we will read what you provided.
We are in early stage so PR won't come before we understood fully all process and code and I will be sure we will raise discussion before submit anything to be online with you.

The davinci is Due based but with specific variant.cpp and firmware is repetier based, I already implemented your commands in FW and modified board.py to change G1 command and conflicted commands M50:
"""Board class. For accessing to the scanner board
    Mofified for Davinci AiO support
    Gcode commands:
        G201 Fnnn : feed rate
        G201 Xnnn : move motor in mm
        G201 Ennn : move motor in deg
        G50     : reset origin position
        M17     : motor_disable
        M18     : motor_enable
        M70 Tn  : switch off laser n, 0 index based
        M71 Tn  : switch on laser n, 0 index based 
        M60 Tn  : read ldr sensor, actually fake just return 500
    """
Acceleration is no supported for this additional motor yet so command do nothing

yes the support of 2 cams will be tricky so we start to support one first :smile: 

here the cams / lasers / and whites led on both sides for your reference:
![image](https://files.gitter.im/luc-github/Repetier-Firmware-0.92/AiOScanner/p6WJ/cam1.png)
![image](https://files.gitter.im/luc-github/Repetier-Firmware-0.92/AiOScanner/dpuu/cam2.png)
![image](https://cloud.githubusercontent.com/assets/8822552/15777255/16698b64-298e-11e6-9b1f-ef5415cdcd45.png)

and because unlike ciclop the turn plate is not a direct drive :
![image](https://files.gitter.im/luc-github/Repetier-Firmware-0.92/AiOScanner/wqUd/plateau-systeme.png)
![image](https://cloud.githubusercontent.com/assets/8822552/15777322/90b574f0-298e-11e6-9a88-1de895a4c7d3.png)

we noticed motor speed is hard coded in moving_calibration.py and autocheck.py and do not always refere to json profile is that normal ?

**Comment by Jesus89** [comment]
Thanks for the information.

As I see in the pictures, the calibration code must be updated to allow only one laser. It is prepared for that, but it needs to be parametric and do some tests.

Also I will support soon parametric values for moving_calibration and autocheck, as a "Rotation parameters" panel like in the Scanning workbench.

**Comment by luc-github** [comment]
yes currently only one laser / cam is used at once for calibration
excellent thanks a lot :smile: let us know if you need some test/feedback to be done

**Comment by Jesus89** [comment]
I also recommend you to use Ubuntu for development. You can run the application directly from the sources instead of creating a specific release. Here is the information if you are interested: https://github.com/bqlabs/horus/blob/develop/doc/development/ubuntu.md.

**Comment by luc-github** [comment]
Thanks a lot

**Comment by luc-github** [comment]
Hi Jesus you said :

>As I see in the pictures, the calibration code must be updated to allow only one laser. It is prepared for that, but it needs to be parametric and do some tests.

>Also I will support soon parametric values for moving_calibration and autocheck, as a "Rotation parameters" panel like in the Scanning workbench.

Do you have estimated time frame ? I am not pushing but I just want to know when  organize tests on our side

Thanks

**Comment by Jesus89** [comment]
Hi, now this is a low priority issue. I am focused on the support of Ciclop-like scanners. Probably in July I will have some time to spend on this.

However, I think you can advance in your research using the provided scientific information and source code. Also if you obtain your calibration parameters from other ways, you can set manually the calibration profile and test the gui.

Note: Rotation parameters are now implemented in the Calibration workbench.

Regards.

**Comment by luc-github** [comment]
Hi Jesus noted - and thanks a lot

I just saw it (https://github.com/bqlabs/horus/commit/3bad6650b5dca89edae8a66378000101309cecd9) in branch release/0.2 - so this the branch we need to follow for all update, right ? not develop branch

**Comment by Jesus89** [comment]
Yes, now development is in the release/0.2 branch. When released, it will be merged with develop.

I will note and close this issue.
