### ISSUE TITLE
OSX bluetooth connection issue

### ISSUE THREAD

**Issue by giodi1973** [bqlabs/horus#80]
using horus 0.2rc1 with OS X 10.10.5
upgrading from 0.2b3 to 0.2rc1, bluetooth communication happens, but horus responds with a "wrong firmware" error message.
Following the message suggestion, I've upgraded the fw, but the error persisted.
ps: I've upgraded the fw two times, the first time using bluetooth.
![settings](https://cloud.githubusercontent.com/assets/19651077/15651943/10113914-2683-11e6-9b00-308d4713e901.png)
![scanner connected](https://cloud.githubusercontent.com/assets/19651077/15651946/13db381a-2683-11e6-83b4-38adfd78be03.png)
![error message](https://cloud.githubusercontent.com/assets/19651077/15651947/15a9c166-2683-11e6-90f7-f42d15a896d3.png)

**Comment by Jesus89** [comment]
Hi,

In this case you have selected a wrong baud rate. BT firmware needs 19200 while default firmware uses 115200.

Also there is a new firmware version that you can download here for bluetooth: https://github.com/bqlabs/horus-fw/releases/tag/0.2. Upload it in Preferences > Binary file > External file.

Regards.

**Comment by giodi1973** [comment]
Thanks a lot and sorry for my misunderstanding.
I haven't noticed the upgraded fw-bt upgraded file.
Now the scanner BT works again.
BR
Giovanni

**Comment by Jesus89** [comment]
Great! Thanks to you.
