### ISSUE TITLE
Conect to CNCShield?

### ISSUE THREAD

**Issue by thjansen72** [bqlabs/horus#85]
Is it possible just to copy code from the 0.1.x firmware (CPU_map.h the cnc-shield-v3 section) to the 0.2x firmware.
Otherwise I let Horus update the firmware and nothing will run....

**Comment by thjansen72** [comment]
Yes, it is possible! Copy code from 0.1 to 0.2, modify the config.h for the board and it runs!

**Comment by wizyke** [comment]
Hello @thjansen72, could You help me please with that issue, I don't have the old version, and can't find it on the internet. Did You managed to get it work? I have the same problem as You. Thank You in advance

**Comment by thjansen72** [comment]
You cab find version 0.1 here: https://github.com/swindonmakers/horus-fw
Or just insert:
//+++++++++++++++
#ifdef CPU_MAP_ATMEGA328P_CNCV3 // Arduino Uno for CNC Shield V3

  // Serial port pins
  #define SERIAL_RX USART_RX_vect
  #define SERIAL_UDRE USART_UDRE_vect

  // Define laser pulse output pins. NOTE: All laser pins must be on the same port.
  #define LASER_DDR       DDRD
  #define LASER_PORT      PORTD
  #define LASER1_BIT      4  // Uno Digital Pin 4        Driver Z-STEP
  #define LASER2_BIT      7  // Uno Digital Pin 7        Driver Z-DIR
  #define LASER3_BIT      4  // Uno Digital Pin 4
  #define LASER4_BIT      7  // Uno Digital Pin 7
  #define LASER_MASK      ((1<<LASER1_BIT)|(1<<LASER2_BIT)) // All step bits

  // Define step pulse output pins. NOTE: All step bit pins must be on the same port.
  #define STEP_DDR        DDRD
  #define STEP_PORT       PORTD
  #define X_STEP_BIT      2  // Uno Digital Pin 2
  #define STEP_MASK       (1<<X_STEP_BIT) // All step bits

  // Define step direction output pins. NOTE: All direction pins must be on the same port.
  #define DIRECTION_DDR     DDRD
  #define DIRECTION_PORT    PORTD
  #define X_DIRECTION_BIT   5  // Uno Digital Pin 5
  #define DIRECTION_MASK    (1<<X_DIRECTION_BIT) // All direction bits

  // Define stepper driver enable/disable output pin (all axis)
  #define STEPPERS_DISABLE_DDR    DDRB
  #define STEPPERS_DISABLE_PORT   PORTB
  #define STEPPERS_DISABLE_BIT    0  // Uno Digital Pin 8
  #define STEPPERS_DISABLE_MASK   (1<<STEPPERS_DISABLE_BIT)

  // Define probe switch input pin.
  #define PROBE_DDR       DDRC
  #define PROBE_PIN       PINC
  #define PROBE_PORT      PORTC
  #define PROBE_BIT       5  // Uno Analog Pin 5        ?????????????????????
  #define PROBE_MASK      (1<<PROBE_BIT)

#endif
//+++++++++++++++

dont forget to modify the config.h (Board name cpu_map_amte......CNCv3). Compile, transfer should run.

**Comment by wizyke** [comment]
Hey,
Thank You for the fast replay, unfortunately, I can not compile the files, since I am not a programmer. Can I download them somewhere?

**Comment by thjansen72** [comment]
I try to send  you the Binary tomorrow.  In this case compiling  means to let the arduino-ide do its Job.


Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: wizyke <notifications@github.com> 
Datum: 12.07.2016  22:21  (GMT+01:00) 
An: bqlabs/horus <horus@noreply.github.com> 
Cc: thjansen72 <thomas@thjansen.de>, Mention <mention@noreply.github.com> 
Betreff: Re: [bqlabs/horus] Conect to CNCShield? (#85) 

Hey,

Thank You for the fast replay, unfortunately, I can not compile the files, since I am not a programmer. Can I download them somewhere?

**Comment by wizyke** [comment]
Thank You in advance!

**Comment by thjansen72** [comment]
[02.zip](https://github.com/bqlabs/horus/files/360903/02.zip)
 In this archieve you'll find the modified source-code (with CNC-V3) and two binary files ("*.hex") - I got no idea, wiitch to use (with or without bootloader) 'cause I' normaly use the arduino -ide.
Take one of the hex-files and copy it - with renaming and replacing - to programs/horus/res/firmware/horus-fw.hex
Now you can use the Horus Program to transfrer the firmware (edit/options). Or just unpack the archive and oen the Horus-fw.ino with the IDE.  Config board anad port. I click and ready.....
Have  fun!

**Comment by wizyke** [comment]
Hello,
I don't know who You are, where are You from, but big thank You for that. I managed to upload and start using the CNC shield.
But now I have an other problem, maybe I shouldn't address it to You, but maybe You can help faster.
The problem is that after calibration, I start to make the scan, and I got a chaos for mesh.
Please take a look to the pic. Any suggestions?
Thank You in advance!
![new picture](https://cloud.githubusercontent.com/assets/20424930/16809924/b5645238-492a-11e6-9b27-0d1d648b8600.jpg)

**Comment by thjansen72** [comment]
I see a lot of refecting material. The black bottom is not ideal. Try to take it step by step.
I'd start with a non-texture scanning just looking for the form (maybe with only one laser),
Try a constant dark bakground - I used a towel the first times, to reduce the vertrix.
You can find more tips here:
https://it-bqcom15-media.s3.amazonaws.com/prod/resources/manual/Horus_Guide_for_Optimum_Scanning-1437403443.pdf

**Comment by wizyke** [comment]
Thank You for the info! Have a nice day!
