### ISSUE TITLE
can Horus make a 3D model out of pictures?

### ISSUE THREAD

**Issue by TylonHH** [bqlabs/horus#99]
Hi,
I guess I'm totally wrong but I don't wanna miss to ask.
I have serveral pictures from an model from a lot of views (on the same level). Like taken pictures while the object is spinning.
Can Horus make out of that pictures a mesh like [PhotoScan from Agisoft](http://www.agisoft.com/features/standard-edition/).

**Comment by ChrisCoxArt** [comment]
No. That requires a very, very different piece of software.
